/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.gitee.wanywhn.EveryLauncher.xml -i dbusproxy.h -a EveryLauncherAdaptor -l DBusProxy
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "EveryLauncherAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class EveryLauncherAdaptor
 */

EveryLauncherAdaptor::EveryLauncherAdaptor(DBusProxy *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

EveryLauncherAdaptor::~EveryLauncherAdaptor()
{
    // destructor
}

void EveryLauncherAdaptor::IndexChangeFiles(const QStringList &paths)
{
    // handle method call com.gitee.wanywhn.EveryLauncher.IndexChangeFiles
    parent()->IndexChangeFiles(paths);
}

void EveryLauncherAdaptor::showWindow()
{
    // handle method call com.gitee.wanywhn.EveryLauncher.showWindow
    parent()->showWindow();
}

